# GENERATED FILE — do not edit manually.
# Run: python scripts/generate.py

# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   timestamp: 2026-07-08T13:55:30+00:00

from __future__ import annotations

from datetime import time
from enum import Enum
from typing import Annotated, Any

from pydantic import AnyUrl, AwareDatetime, EmailStr, Field, RootModel

from netdoc_sdk.models.core import APIModel


class ARPEntry(APIModel):
    id: str
    device: Annotated[str, Field(description='The device this entry belongs to.')]
    device_hostname: str
    vrf: Annotated[str | None, Field(description='VRF context.')] = None
    vrf_name: str | None = None
    ip_address: Annotated[str, Field(description='IP address.')]
    mac_address: Annotated[
        str, Field(description='Resolved MAC address (AA:BB:CC:DD:EE:FF).', max_length=17)
    ]
    interface: Annotated[str, Field(description='Interface where this was learned.')]
    interface_name: str | None = None


class AdminStateEnum(Enum):
    down = 'down'
    up = 'up'


class AuditLogDetail(APIModel):
    id: Annotated[str, Field(description='Unique identifier for the audit log.')]
    tenant_id: Annotated[
        str | None, Field(description='Denormalised tenant id (no foreign key).')
    ] = None
    tenant_name: Annotated[
        str | None, Field(description='Denormalised tenant name at the time of the event.')
    ] = None
    source_ip: Annotated[str, Field(description='Source IP address.', title='Source IP address')]
    user_id: Annotated[str | None, Field(description='Denormalised user id (no foreign key).')] = (
        None
    )
    username: str | None = None
    action: Annotated[str, Field(description='The HTTP method (POST, PUT, PATCH, DELETE).')]
    resource_path: Annotated[str, Field(description='The API path that was accessed.')]
    status_code: Annotated[int, Field(description='The HTTP response status code.')]
    duration_ms: Annotated[
        float, Field(description='Request duration in milliseconds.', title='Duration (ms)')
    ]
    created_at: Annotated[AwareDatetime, Field(description='When the log was created.')]


class AuthToken(APIModel):
    token: str


class AuthTokenRequest(APIModel):
    username: Annotated[str, Field(min_length=1)]
    password: Annotated[str, Field(min_length=1)]


class BlankEnum(Enum):
    field_ = ''


class DomainRange(RootModel[str]):
    root: Annotated[str, Field(max_length=64)]


class NetworkRange(RootModel[str]):
    root: Annotated[str, Field(max_length=32)]


class CollectorDetail(APIModel):
    id: str
    user: Annotated[str, Field(description='Collector user that authenticates API calls.')]
    name: Annotated[str, Field(description='Stable collector instance name.')]
    version: Annotated[str, Field(title='Agent version')]
    is_active: bool | None = None
    canonical_devices: Annotated[
        list[str] | None, Field(title='Statically associated Canonical Devices')
    ] = None
    sites: Annotated[list[str] | None, Field(title='Statically associated Sites')] = None
    domain_ranges: Annotated[
        list[DomainRange] | None, Field(title='Statically associated domains')
    ] = None
    network_ranges: Annotated[
        list[NetworkRange] | None, Field(title='Statically associated network ranges')
    ] = None
    created_at: Annotated[AwareDatetime, Field(description='When the collector was created.')]
    updated_at: Annotated[AwareDatetime, Field(description='When the collector was last updated.')]
    last_heartbeat_at: AwareDatetime | None = None


class DomainRange1(RootModel[str]):
    root: Annotated[str, Field(max_length=64, min_length=1)]


class NetworkRange1(RootModel[str]):
    root: Annotated[str, Field(max_length=32, min_length=1)]


class CollectorDetailRequest(APIModel):
    is_active: bool | None = None
    canonical_devices: Annotated[
        list[str] | None, Field(title='Statically associated Canonical Devices')
    ] = None
    sites: Annotated[list[str] | None, Field(title='Statically associated Sites')] = None
    domain_ranges: Annotated[
        list[DomainRange1] | None, Field(title='Statically associated domains')
    ] = None
    network_ranges: Annotated[
        list[NetworkRange1] | None, Field(title='Statically associated network ranges')
    ] = None


class DomainRange2(RootModel[str]):
    root: Annotated[str, Field(max_length=64)]


class NetworkRange2(RootModel[str]):
    root: Annotated[str, Field(max_length=32)]


class CollectorList(APIModel):
    id: str
    user: Annotated[str, Field(description='Collector user that authenticates API calls.')]
    name: Annotated[str, Field(description='Stable collector instance name.')]
    version: Annotated[str, Field(title='Agent version')]
    is_active: bool
    canonical_devices: Annotated[list[str], Field(title='Statically associated Canonical Devices')]
    sites: Annotated[list[str], Field(title='Statically associated Sites')]
    domain_ranges: Annotated[list[DomainRange2], Field(title='Statically associated domains')]
    network_ranges: Annotated[
        list[NetworkRange2], Field(title='Statically associated network ranges')
    ]
    created_at: Annotated[AwareDatetime, Field(description='When the collector was created.')]
    updated_at: Annotated[AwareDatetime, Field(description='When the collector was last updated.')]
    last_heartbeat_at: AwareDatetime | None = None


class ConnectionType127Enum(Enum):
    direct = 'direct'
    discovered = 'discovered'
    inferred = 'inferred'


class ConnectionTypeEc9Enum(Enum):
    physical = 'physical'
    logical = 'logical'
    virtual = 'virtual'


class CredentialDetail(APIModel):
    id: Annotated[str, Field(description='Unique identifier for the credential.')]
    label: Annotated[
        str,
        Field(
            description='Human-readable label for this credential.',
            max_length=255,
            pattern='^[\\w\\s\\-]+$',
        ),
    ]
    description: Annotated[
        str | None, Field(description='Detailed description of what this credential contains.')
    ] = None
    username: Annotated[
        str | None, Field(description='Username used to login.', max_length=100)
    ] = None
    verify_cert: Annotated[
        bool | None, Field(description='Validate certificate', title='Verify cert?')
    ] = None
    created_at: Annotated[AwareDatetime, Field(description='When the credential was created.')]
    updated_at: Annotated[AwareDatetime, Field(description='When the credential was last updated.')]


class CredentialDetailRequest(APIModel):
    label: Annotated[
        str,
        Field(
            description='Human-readable label for this credential.',
            max_length=255,
            min_length=1,
            pattern='^[\\w\\s\\-]+$',
        ),
    ]
    description: Annotated[
        str | None, Field(description='Detailed description of what this credential contains.')
    ] = None
    username: Annotated[
        str | None, Field(description='Username used to login.', max_length=100)
    ] = None
    password: Annotated[str | None, Field(min_length=1)] = None
    secret: Annotated[str | None, Field(min_length=1)] = None
    verify_cert: Annotated[
        bool | None, Field(description='Validate certificate', title='Verify cert?')
    ] = None


class CredentialList(APIModel):
    id: Annotated[str, Field(description='Unique identifier for the credential.')]
    label: Annotated[str, Field(description='Human-readable label for this credential.')]
    description: Annotated[
        str, Field(description='Detailed description of what this credential contains.')
    ]
    username: Annotated[str | None, Field(description='Username used to login.')] = None
    verify_cert: Annotated[bool, Field(description='Validate certificate', title='Verify cert?')]
    created_at: Annotated[AwareDatetime, Field(description='When the credential was created.')]
    updated_at: Annotated[AwareDatetime, Field(description='When the credential was last updated.')]


class DeviceModel(RootModel[str]):
    root: Annotated[str, Field(max_length=32)]


class SerialNumber(RootModel[str]):
    root: Annotated[str, Field(max_length=32)]


class DiscoveredVia09dEnum(Enum):
    arp = 'arp'
    mac_table = 'mac_table'
    dhcp = 'dhcp'
    lldp = 'lldp'
    cdp = 'cdp'
    manual = 'manual'
    api = 'api'


class DiscoveredVia9dcEnum(Enum):
    inferred = 'inferred'
    lldp = 'lldp'
    cdp = 'cdp'
    manual = 'manual'
    arp = 'arp'
    mac_table = 'mac_table'


class DiscoveryJobClaim(APIModel):
    id: Annotated[str, Field(description='Unique identifier for the job.')]
    run: Annotated[str, Field(description='Associated discovery run.', title='Discovery')]
    claim_token: Annotated[
        str | None, Field(description='Claim token used to authorize the collector.')
    ] = None
    idempotency_key: Annotated[str, Field(description='Idempotency key.')]
    inventory: dict[str, Any]


class DiscoveryJobCompleteStatusEnum(Enum):
    completed = 'completed'
    failed = 'failed'
    cancelled = 'cancelled'


class DiscoveryModeEnum(Enum):
    netmiko_allied_telesis_awplus_ssh = 'netmiko:allied_telesis:awplus:ssh'
    netmiko_aruba_aoscx_ssh = 'netmiko:aruba:aoscx:ssh'
    netmiko_cisco_ios_ssh = 'netmiko:cisco:ios:ssh'
    netmiko_cisco_ios_telnet = 'netmiko:cisco:ios:telnet'
    netmiko_cisco_nxos_ssh = 'netmiko:cisco:nxos:ssh'
    netmiko_cisco_xr_ssh = 'netmiko:cisco_xr:ssh'
    netmiko_hp_comware_ssh = 'netmiko:hp:comware:ssh'
    netmiko_hp_procurve_ssh = 'netmiko:hp:procurve:ssh'
    netmiko_hp_procurve_telnet = 'netmiko:hp:procurve:telnet'
    netmiko_huawei_vrp_ssh = 'netmiko:huawei:vrp:ssh'
    netmiko_linux__ssh = 'netmiko:linux::ssh'
    netdoc_panw_ngfw_https = 'netdoc:panw:ngfw:https'
    netdoc_vmware_vsphere_https = 'netdoc:vmware:vsphere:https'


class DiscoveryRunDetailStatusEnum(Enum):
    pending = 'pending'
    running = 'running'
    cancelling = 'cancelling'
    cancelled = 'cancelled'
    completed = 'completed'
    failed = 'failed'


class DiscoverySchedule(APIModel):
    id: str
    name: Annotated[str, Field(max_length=255)]
    enabled: bool | None = None
    daily_time: time
    next_run_at: AwareDatetime | None = None
    last_run_at: AwareDatetime | None = None
    last_status: str
    created_at: AwareDatetime
    updated_at: AwareDatetime


class DiscoveryScheduleRequest(APIModel):
    name: Annotated[str, Field(max_length=255, min_length=1)]
    enabled: bool | None = None
    daily_time: time
    next_run_at: AwareDatetime | None = None


class EndpointConnectionDetail(APIModel):
    id: Annotated[str, Field(description='Unique identifier for the connection.')]
    snapshot: Annotated[str, Field(description='The snapshot this data belongs to.')]
    endpoint_interface: Annotated[str, Field(description='The endpoint interface.')]
    endpoint_name: str
    endpoint_interface_mac: str
    endpoint_interface_name: str
    network_interface: Annotated[str, Field(description='The network device interface.')]
    device: str
    network_interface_name: str
    connection_type: Annotated[
        ConnectionType127Enum | None,
        Field(
            description='Type of connection.\n\n* `direct` - Direct\n* `discovered` - Discovered\n* `inferred` - Inferred'
        ),
    ] = None
    discovered_via: Annotated[
        DiscoveredVia9dcEnum | None,
        Field(
            description='How the connection was discovered.\n\n* `inferred` - Inferred\n* `lldp` - LLDP\n* `cdp` - CDP\n* `manual` - Manual\n* `arp` - ARP Table\n* `mac_table` - MAC Address Table'
        ),
    ] = None


class EndpointConnectionList(APIModel):
    id: Annotated[str, Field(description='Unique identifier for the connection.')]
    endpoint_interface: Annotated[str, Field(description='The endpoint interface.')]
    endpoint_name: str
    endpoint_interface_mac: str
    network_interface: Annotated[str, Field(description='The network device interface.')]
    device: str
    network_interface_name: str
    connection_type: Annotated[
        ConnectionType127Enum | None,
        Field(
            description='Type of connection.\n\n* `direct` - Direct\n* `discovered` - Discovered\n* `inferred` - Inferred'
        ),
    ] = None
    discovered_via: Annotated[
        DiscoveredVia9dcEnum | None,
        Field(
            description='How the connection was discovered.\n\n* `inferred` - Inferred\n* `lldp` - LLDP\n* `cdp` - CDP\n* `manual` - Manual\n* `arp` - ARP Table\n* `mac_table` - MAC Address Table'
        ),
    ] = None


class EndpointIPAddress(APIModel):
    id: Annotated[str, Field(description='Unique identifier for the endpoint IP address.')]
    address: Annotated[str, Field(description='IP address (IPv4 or IPv6). Not unique.')]
    prefix_length: Annotated[
        int | None,
        Field(
            description='Subnet prefix length (0-32 for IPv4, 0-128 for IPv6).',
            ge=-2147483648,
            le=2147483647,
        ),
    ] = None
    cidr: Annotated[str, Field(description='Return CIDR notation.')]
    vrf: Annotated[
        str | None, Field(description='VRF this IP belongs to (for routing context).')
    ] = None
    vrf_name: str | None = None


class EndpointInterface(APIModel):
    id: Annotated[str, Field(description='Unique identifier for the endpoint interface.')]
    name: Annotated[
        str | None, Field(description='Interface name (eth0, ens192, etc.).', max_length=100)
    ] = None
    mac_address: Annotated[
        str | None,
        Field(description='Interface MAC address (AA:BB:CC:DD:EE:FF). Not unique.', max_length=17),
    ] = None
    vlan: Annotated[str | None, Field(description='VLAN this interface is in.')] = None
    vlan_id: int | None = None
    is_primary: Annotated[
        bool | None, Field(description='Whether this is the primary interface.')
    ] = None
    ip_addresses: list[EndpointIPAddress]


class EndpointTypeEnum(Enum):
    server = 'server'
    client = 'client'
    vm = 'vm'
    storage = 'storage'
    iot = 'iot'
    printer = 'printer'
    phone = 'phone'
    other = 'other'


class EntryTypeEnum(Enum):
    dynamic = 'dynamic'
    static = 'static'


class HypervisorTypeEnum(Enum):
    vsphere = 'vsphere'
    hyperv = 'hyperv'
    kvm = 'kvm'
    aws = 'aws'
    azure = 'azure'
    gcp = 'gcp'
    docker = 'docker'
    kubernetes = 'kubernetes'
    baremetal = 'baremetal'
    unknown = 'unknown'


class IPAddress(APIModel):
    id: str
    interface: Annotated[str, Field(description='The interface this IP is assigned to.')]
    interface_name: str
    address: Annotated[str, Field(description='IP address (IPv4 or IPv6).')]
    prefix_length: Annotated[
        int,
        Field(
            description='Subnet prefix length (0-32 for IPv4, 0-128 for IPv6).',
            ge=-2147483648,
            le=2147483647,
        ),
    ]
    cidr: str
    vrf: Annotated[str | None, Field(description='VRF this IP belongs to.')] = None
    vrf_name: str | None = None
    is_secondary: Annotated[
        bool | None, Field(description='Whether this is a secondary address.')
    ] = None


class IconEnum(Enum):
    firewall = 'firewall'
    load_balancer = 'load-balancer'
    phone = 'phone'
    router = 'router'
    router_modular = 'router-modular'
    switch_l2 = 'switch-l2'
    switch_l3 = 'switch-l3'
    switch_modular = 'switch-modular'
    wireless_ap = 'wireless-ap'
    wireless_controller = 'wireless-controller'
    workstation = 'workstation'


class InterfaceDetailTunnelTypeEnum(Enum):
    geneve = 'geneve'
    gre = 'gre'
    ipsec = 'ipsec'
    mpls = 'mpls'
    none = 'none'
    other = 'other'
    vxlan = 'vxlan'


class InterfaceTypeEnum(Enum):
    loopback = 'loopback'
    management = 'management'
    nve = 'nve'
    other = 'other'
    physical = 'physical'
    port_channel = 'port_channel'
    subinterface = 'subinterface'
    tunnel = 'tunnel'
    virtual = 'virtual'
    vlan_svi = 'vlan_svi'


class LevelEnum(Enum):
    debug = 'DEBUG'
    info = 'INFO'
    warning = 'WARNING'
    error = 'ERROR'
    critical = 'CRITICAL'


class LogRecordDetail(APIModel):
    id: Annotated[str, Field(description='Unique identifier for the log record.')]
    logger_name: Annotated[str, Field(description='Name of the logger that emitted the record.')]
    tenant_id: Annotated[
        str | None, Field(description='Denormalised tenant id (no foreign key).')
    ] = None
    tenant_name: Annotated[
        str | None, Field(description='Denormalised tenant name at the time of the event.')
    ] = None
    user_id: Annotated[str | None, Field(description='Denormalised user id (no foreign key).')] = (
        None
    )
    username: Annotated[
        str | None, Field(description='Denormalised username at the time of the event.')
    ] = None
    created_at: Annotated[AwareDatetime, Field(description='When the log record was created.')]
    correlation_id: Annotated[
        str | None, Field(description='Correlation id linking records from one request or job.')
    ] = None
    object_type: Annotated[
        str | None,
        Field(description="Label of the referenced object's model (e.g. 'inventory.Device')."),
    ] = None
    object_id: Annotated[
        str | None, Field(description='Primary key of the referenced object, as a string.')
    ] = None
    object_label: Annotated[
        str | None, Field(description='Human-readable label of the referenced object.')
    ] = None
    level: Annotated[
        LevelEnum,
        Field(
            description='Severity level of the log record.\n\n* `DEBUG` - Debug\n* `INFO` - Info\n* `WARNING` - Warning\n* `ERROR` - Error\n* `CRITICAL` - Critical'
        ),
    ]
    message: Annotated[str, Field(description='The formatted log message.')]
    context: Annotated[
        Any | None, Field(description='Arbitrary structured context for the event.')
    ] = None
    exception_type: Annotated[
        str | None,
        Field(
            description='Exception class name, when the record captured an exception.',
            max_length=255,
        ),
    ] = None
    traceback: Annotated[str | None, Field(description='Formatted traceback, when available.')] = (
        None
    )
    module: Annotated[
        str | None, Field(description='Module that emitted the record.', max_length=255)
    ] = None
    func_name: Annotated[
        str | None,
        Field(
            description='Function that emitted the record.', max_length=255, title='Function name'
        ),
    ] = None
    line_no: Annotated[
        int | None,
        Field(
            description='Source line number that emitted the record.',
            ge=-2147483648,
            le=2147483647,
            title='Line number',
        ),
    ] = None
    hostname: Annotated[
        str | None,
        Field(description='Hostname of the process that emitted the record.', max_length=255),
    ] = None
    process: Annotated[
        int | None,
        Field(description='Process id that emitted the record.', ge=-2147483648, le=2147483647),
    ] = None
    thread_name: Annotated[
        str | None, Field(description='Thread name that emitted the record.', max_length=255)
    ] = None


class MACEntry(APIModel):
    id: str
    device: Annotated[str, Field(description='The device this entry belongs to.')]
    device_hostname: str
    vlan: Annotated[str, Field(description='VLAN context.')]
    vlan_id: int | None = None
    mac_address: Annotated[
        str, Field(description='MAC address (AA:BB:CC:DD:EE:FF).', max_length=17)
    ]
    interface: Annotated[str, Field(description='Interface where this MAC was learned.')]
    interface_name: str | None = None
    entry_type: Annotated[
        EntryTypeEnum | None,
        Field(
            description='Dynamic or static entry.\n\n* `dynamic` - Dynamic\n* `static` - Static',
            title='Type',
        ),
    ] = None


class NullEnum(Enum):
    none_type_none = None


class OperStateEnum(Enum):
    down = 'down'
    unknown = 'unknown'
    up = 'up'


class OriginEnum(Enum):
    manual = 'manual'
    scheduled = 'scheduled'


class PaginatedARPEntryList(APIModel):
    count: Annotated[int, Field(examples=[123])]
    next: Annotated[AnyUrl | None, Field(examples=['http://api.example.org/accounts/?page=4'])] = (
        None
    )
    previous: Annotated[
        AnyUrl | None, Field(examples=['http://api.example.org/accounts/?page=2'])
    ] = None
    results: list[ARPEntry]


class PaginatedAuditLogDetailList(APIModel):
    count: Annotated[int, Field(examples=[123])]
    next: Annotated[AnyUrl | None, Field(examples=['http://api.example.org/accounts/?page=4'])] = (
        None
    )
    previous: Annotated[
        AnyUrl | None, Field(examples=['http://api.example.org/accounts/?page=2'])
    ] = None
    results: list[AuditLogDetail]


class PaginatedCollectorListList(APIModel):
    count: Annotated[int, Field(examples=[123])]
    next: Annotated[AnyUrl | None, Field(examples=['http://api.example.org/accounts/?page=4'])] = (
        None
    )
    previous: Annotated[
        AnyUrl | None, Field(examples=['http://api.example.org/accounts/?page=2'])
    ] = None
    results: list[CollectorList]


class PaginatedCredentialListList(APIModel):
    count: Annotated[int, Field(examples=[123])]
    next: Annotated[AnyUrl | None, Field(examples=['http://api.example.org/accounts/?page=4'])] = (
        None
    )
    previous: Annotated[
        AnyUrl | None, Field(examples=['http://api.example.org/accounts/?page=2'])
    ] = None
    results: list[CredentialList]


class PaginatedDiscoveryScheduleList(APIModel):
    count: Annotated[int, Field(examples=[123])]
    next: Annotated[AnyUrl | None, Field(examples=['http://api.example.org/accounts/?page=4'])] = (
        None
    )
    previous: Annotated[
        AnyUrl | None, Field(examples=['http://api.example.org/accounts/?page=2'])
    ] = None
    results: list[DiscoverySchedule]


class PaginatedEndpointConnectionListList(APIModel):
    count: Annotated[int, Field(examples=[123])]
    next: Annotated[AnyUrl | None, Field(examples=['http://api.example.org/accounts/?page=4'])] = (
        None
    )
    previous: Annotated[
        AnyUrl | None, Field(examples=['http://api.example.org/accounts/?page=2'])
    ] = None
    results: list[EndpointConnectionList]


class PaginatedIPAddressList(APIModel):
    count: Annotated[int, Field(examples=[123])]
    next: Annotated[AnyUrl | None, Field(examples=['http://api.example.org/accounts/?page=4'])] = (
        None
    )
    previous: Annotated[
        AnyUrl | None, Field(examples=['http://api.example.org/accounts/?page=2'])
    ] = None
    results: list[IPAddress]


class PaginatedLogRecordDetailList(APIModel):
    count: Annotated[int, Field(examples=[123])]
    next: Annotated[AnyUrl | None, Field(examples=['http://api.example.org/accounts/?page=4'])] = (
        None
    )
    previous: Annotated[
        AnyUrl | None, Field(examples=['http://api.example.org/accounts/?page=2'])
    ] = None
    results: list[LogRecordDetail]


class PaginatedMACEntryList(APIModel):
    count: Annotated[int, Field(examples=[123])]
    next: Annotated[AnyUrl | None, Field(examples=['http://api.example.org/accounts/?page=4'])] = (
        None
    )
    previous: Annotated[
        AnyUrl | None, Field(examples=['http://api.example.org/accounts/?page=2'])
    ] = None
    results: list[MACEntry]


class PatchedCanonicalDeviceDetailRequest(APIModel):
    label: Annotated[
        str | None,
        Field(
            description='Display name.',
            max_length=255,
            min_length=1,
            pattern='^(?:[a-zA-Z0-9_](?:[a-zA-Z0-9\\-_]{0,61}[a-zA-Z0-9_])?\\.)+[a-zA-Z]{2,}$|^[a-zA-Z0-9_](?:[a-zA-Z0-9\\-_]{0,61}[a-zA-Z0-9_])?$',
        ),
    ] = None
    icon: Annotated[
        IconEnum | BlankEnum | NullEnum | None,
        Field(
            description='Icon used to represent the device in topologies.\n\n* `firewall` - Firewall\n* `load-balancer` - Load Balancer\n* `phone` - Phone\n* `router` - Router\n* `router-modular` - Modular Router\n* `switch-l2` - Switch L2\n* `switch-l3` - Switch L3\n* `switch-modular` - Modular Switch\n* `wireless-ap` - Wireless Access Point\n* `wireless-controller` - Wireless Controller\n* `workstation` - Workstation'
        ),
    ] = None
    mgmt_address: Annotated[
        str | None,
        Field(
            description='Primary address for discovery.', max_length=255, title='Management address'
        ),
    ] = None
    discovery_mode: Annotated[
        DiscoveryModeEnum | BlankEnum | NullEnum | None,
        Field(
            description='Discovery mode.\n\n* `netmiko:allied_telesis:awplus:ssh` - Allied Telesis AW+ (SSH)\n* `netmiko:aruba:aoscx:ssh` - Aruba AOSCX (SSH)\n* `netmiko:cisco:ios:ssh` - Cisco IOS XE (SSH)\n* `netmiko:cisco:ios:telnet` - Cisco IOS XE (Telnet)\n* `netmiko:cisco:nxos:ssh` - Cisco NX-OS (SSH)\n* `netmiko:cisco_xr:ssh` - Cisco XR (SSH)\n* `netmiko:hp:comware:ssh` - HPE Comware (SSH)\n* `netmiko:hp:procurve:ssh` - HPE Procurve (SSH)\n* `netmiko:hp:procurve:telnet` - HPE Procurve (Telnet)\n* `netmiko:huawei:vrp:ssh` - Huawei VRP (SSH)\n* `netmiko:linux::ssh` - Linux (SSH)\n* `netdoc:panw:ngfw:https` - Palo Alto Networks NGFW (HTTPs)\n* `netdoc:vmware:vsphere:https` - VMware vSphere (HTTPs)'
        ),
    ] = None
    is_discoverable: Annotated[
        bool | None,
        Field(
            description='Whether the device is still actively discovered.', title='Is discoverable?'
        ),
    ] = None
    identifiers: Annotated[
        Any | None, Field(description='Unique identifiers to correlate the device.')
    ] = None
    credential: Annotated[str | None, Field(description='Credential used to discovery.')] = None
    parent: Annotated[
        str | None, Field(description='Parent device for virtual instances (e.g., N7K VDC).')
    ] = None
    site: Annotated[str | None, Field(description='Canonical site/location for this device.')] = (
        None
    )
    role: Annotated[
        str | None,
        Field(
            description='Device role (core, distribution, access, etc.).',
            max_length=100,
            pattern='^[\\w\\s\\-]+$',
        ),
    ] = None


class DomainRange3(RootModel[str]):
    root: Annotated[str, Field(max_length=64, min_length=1)]


class NetworkRange3(RootModel[str]):
    root: Annotated[str, Field(max_length=32, min_length=1)]


class PatchedCollectorDetailRequest(APIModel):
    is_active: bool | None = None
    canonical_devices: Annotated[
        list[str] | None, Field(title='Statically associated Canonical Devices')
    ] = None
    sites: Annotated[list[str] | None, Field(title='Statically associated Sites')] = None
    domain_ranges: Annotated[
        list[DomainRange3] | None, Field(title='Statically associated domains')
    ] = None
    network_ranges: Annotated[
        list[NetworkRange3] | None, Field(title='Statically associated network ranges')
    ] = None


class PatchedCredentialDetailRequest(APIModel):
    label: Annotated[
        str | None,
        Field(
            description='Human-readable label for this credential.',
            max_length=255,
            min_length=1,
            pattern='^[\\w\\s\\-]+$',
        ),
    ] = None
    description: Annotated[
        str | None, Field(description='Detailed description of what this credential contains.')
    ] = None
    username: Annotated[
        str | None, Field(description='Username used to login.', max_length=100)
    ] = None
    password: Annotated[str | None, Field(min_length=1)] = None
    secret: Annotated[str | None, Field(min_length=1)] = None
    verify_cert: Annotated[
        bool | None, Field(description='Validate certificate', title='Verify cert?')
    ] = None


class PatchedDiscoveryScheduleRequest(APIModel):
    name: Annotated[str | None, Field(max_length=255, min_length=1)] = None
    enabled: bool | None = None
    daily_time: time | None = None
    next_run_at: AwareDatetime | None = None


class PatchedSnapshotDetailRequest(APIModel):
    label: Annotated[
        str | None, Field(description='Human-readable label for this snapshot.', max_length=255)
    ] = None
    description: Annotated[
        str | None, Field(description='Detailed description of what this snapshot contains.')
    ] = None
    pinned: Annotated[
        bool | None,
        Field(
            description='Pinned snapshots are exempt from automatic retention deletion.',
            title='Is pinned?',
        ),
    ] = None


class PatchedTenantDetailRequest(APIModel):
    name: Annotated[
        str | None,
        Field(
            description='Human-readable name for the tenant.',
            max_length=255,
            min_length=1,
            pattern='^[\\w\\s\\-]+$',
        ),
    ] = None
    is_active: Annotated[
        bool | None,
        Field(
            description='Whether the tenant is active. Inactive tenants cannot log in.',
            title='Is active?',
        ),
    ] = None
    log_retention_days: Annotated[
        int | None,
        Field(
            description='Maximum number of logs in days.',
            ge=1,
            le=2147483647,
            title='Log retention (days)',
        ),
    ] = None
    max_snapshots: Annotated[
        int | None,
        Field(
            description='Maximum number of stored snapshots.',
            ge=1,
            le=2147483647,
            title='Max. snapshots',
        ),
    ] = None
    snapshot_retention_days: Annotated[
        int | None,
        Field(
            description='Maximum number of snapshot in days.',
            ge=1,
            le=2147483647,
            title='Snapshot retention (days)',
        ),
    ] = None


class PatchedUserProfileRequest(APIModel):
    password: Annotated[str | None, Field(min_length=1)] = None


class ProtocolEnum(Enum):
    connected = 'connected'
    static = 'static'
    bgp = 'bgp'
    eigrp = 'eigrp'
    eigrp_ex = 'eigrp-ex'
    isis = 'isis'
    isis_is = 'isis-is'
    isis_l1 = 'isis-l1'
    isis_l2 = 'isis-l2'
    isis_sum = 'isis-sum'
    local = 'local'
    ospf = 'ospf'
    ospf_e1 = 'ospf-e1'
    ospf_e2 = 'ospf-e2'
    ospf_ia = 'ospf-ia'
    ospf_n1 = 'ospf-n1'
    ospf_n2 = 'ospf-n2'
    rip = 'rip'
    other = 'other'


class RawOutputListStatusEnum(Enum):
    failed = 'failed'
    ignored_after_cancel = 'ignored_after_cancel'
    parsed = 'parsed'
    queued = 'queued'
    received = 'received'
    stale = 'stale'


class RoleEnum(Enum):
    admin = 'admin'
    collector = 'collector'
    operator = 'operator'
    viewer = 'viewer'


class RouteEntry(APIModel):
    id: str
    device: Annotated[str, Field(description='The device this route belongs to.')]
    device_hostname: str
    vrf: Annotated[str | None, Field(description='VRF this route is in.')] = None
    vrf_name: str | None = None
    prefix: Annotated[
        str,
        Field(description='Destination prefix (e.g., 10.0.0.0/8 or 2001:db8::/32).', max_length=50),
    ]
    next_hop: Annotated[str | None, Field(description='Next-hop IP address.')] = None
    next_hop_interface: Annotated[str | None, Field(description='Outgoing interface.')] = None
    next_hop_interface_name: str | None = None
    protocol: Annotated[
        ProtocolEnum,
        Field(
            description='Routing protocol that installed this route.\n\n* `connected` - Connected\n* `static` - Static\n* `bgp` - BGP\n* `eigrp` - EIGRP\n* `eigrp-ex` - EIGRP External\n* `isis` - IS-IS\n* `isis-is` - IS-IS Inter Area\n* `isis-l1` - IS-IS Level-1\n* `isis-l2` - IS-IS Level-2\n* `isis-sum` - IS-IS Summary\n* `local` - local\n* `ospf` - OSPF\n* `ospf-e1` - OSPF External Type 1\n* `ospf-e2` - OSPF External Type 2\n* `ospf-ia` - OSPF Inter Area\n* `ospf-n1` - OSPF NSSA External Type 1\n* `ospf-n2` - OSPF NSSA External Type 2\n* `rip` - RIP\n* `other` - Other'
        ),
    ]
    metric: Annotated[
        int | None,
        Field(description='Route metric.', ge=-9223372036854775808, le=9223372036854775807),
    ] = None
    admin_distance: Annotated[
        int | None, Field(description='Administrative distance.', ge=-2147483648, le=2147483647)
    ] = None
    is_best: Annotated[
        bool | None, Field(description='Whether this is the best route for the prefix.')
    ] = None
    tag: Annotated[
        int | None, Field(description='Route tag.', ge=-9223372036854775808, le=9223372036854775807)
    ] = None
    leaked_from_vrf: Annotated[
        str | None, Field(description='Source VRF if this route was leaked from another VRF.')
    ] = None
    leaked_from_vrf_name: str | None = None


class SiteTypeEnum(Enum):
    datacenter = 'datacenter'
    campus = 'campus'
    cloud = 'cloud'
    branch = 'branch'
    other = 'other'


class StateEnum(Enum):
    active = 'active'
    suspend = 'suspend'


class StatusAc0Enum(Enum):
    cancelled = 'cancelled'
    completed = 'completed'
    failed = 'failed'
    partial = 'partial'
    pending = 'pending'


class StatusF5fEnum(Enum):
    cancelled = 'cancelled'
    cancelling = 'cancelling'
    claimed = 'claimed'
    completed = 'completed'
    expired = 'expired'
    failed = 'failed'
    queued = 'queued'
    running = 'running'


class SwitchportModeEnum(Enum):
    access = 'access'
    hybrid = 'hybrid'
    routed = 'routed'
    trunk = 'trunk'


class TenantDetail(APIModel):
    id: Annotated[str, Field(description='Unique identifier for the tenant.')]
    name: Annotated[
        str,
        Field(
            description='Human-readable name for the tenant.',
            max_length=255,
            pattern='^[\\w\\s\\-]+$',
        ),
    ]
    is_active: Annotated[
        bool | None,
        Field(
            description='Whether the tenant is active. Inactive tenants cannot log in.',
            title='Is active?',
        ),
    ] = None
    log_retention_days: Annotated[
        int | None,
        Field(
            description='Maximum number of logs in days.',
            ge=1,
            le=2147483647,
            title='Log retention (days)',
        ),
    ] = None
    max_snapshots: Annotated[
        int | None,
        Field(
            description='Maximum number of stored snapshots.',
            ge=1,
            le=2147483647,
            title='Max. snapshots',
        ),
    ] = None
    snapshot_retention_days: Annotated[
        int | None,
        Field(
            description='Maximum number of snapshot in days.',
            ge=1,
            le=2147483647,
            title='Snapshot retention (days)',
        ),
    ] = None
    created_at: Annotated[AwareDatetime, Field(description='When the tenant was created.')]
    updated_at: Annotated[AwareDatetime, Field(description='When the tenant was last updated.')]


class TenantDetailRequest(APIModel):
    name: Annotated[
        str,
        Field(
            description='Human-readable name for the tenant.',
            max_length=255,
            min_length=1,
            pattern='^[\\w\\s\\-]+$',
        ),
    ]
    is_active: Annotated[
        bool | None,
        Field(
            description='Whether the tenant is active. Inactive tenants cannot log in.',
            title='Is active?',
        ),
    ] = None
    log_retention_days: Annotated[
        int | None,
        Field(
            description='Maximum number of logs in days.',
            ge=1,
            le=2147483647,
            title='Log retention (days)',
        ),
    ] = None
    max_snapshots: Annotated[
        int | None,
        Field(
            description='Maximum number of stored snapshots.',
            ge=1,
            le=2147483647,
            title='Max. snapshots',
        ),
    ] = None
    snapshot_retention_days: Annotated[
        int | None,
        Field(
            description='Maximum number of snapshot in days.',
            ge=1,
            le=2147483647,
            title='Snapshot retention (days)',
        ),
    ] = None


class TenantList(APIModel):
    id: Annotated[str, Field(description='Unique identifier for the tenant.')]
    name: Annotated[str, Field(description='Human-readable name for the tenant.')]
    is_active: Annotated[
        bool,
        Field(
            description='Whether the tenant is active. Inactive tenants cannot log in.',
            title='Is active?',
        ),
    ]
    log_retention_days: Annotated[
        int, Field(description='Maximum number of logs in days.', title='Log retention (days)')
    ]
    max_snapshots: Annotated[
        int, Field(description='Maximum number of stored snapshots.', title='Max. snapshots')
    ]
    snapshot_retention_days: Annotated[
        int,
        Field(description='Maximum number of snapshot in days.', title='Snapshot retention (days)'),
    ]
    created_at: Annotated[AwareDatetime, Field(description='When the tenant was created.')]
    updated_at: Annotated[AwareDatetime, Field(description='When the tenant was last updated.')]


class TopologyEdge(APIModel):
    id: str
    source: str
    target: str
    source_interface: str
    target_interface: str
    connection_type: str
    edge_type: str
    discovered_via: str
    overlay_vni: int | None = None


class TopologyNode(APIModel):
    id: str
    label: str
    type: str
    vendor: str | None = None
    model: str | None = None
    platform: str | None = None
    site: str | None = None
    role: str | None = None
    mgmt_ip: str | None = None
    endpoint_type: str | None = None
    discovered_via: str | None = None


class TunnelTypeA97Enum(Enum):
    vxlan = 'vxlan'
    geneve = 'geneve'
    gre = 'gre'
    ipsec = 'ipsec'
    mpls = 'mpls'
    other = 'other'


class UserDetail(APIModel):
    id: Annotated[str, Field(description='Unique identifier for the user.')]
    username: Annotated[
        str,
        Field(
            description='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.',
            max_length=150,
            pattern='^[\\w.@+-]+$',
        ),
    ]
    is_active: Annotated[
        bool | None,
        Field(
            description='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.',
            title='Active',
        ),
    ] = None
    role: Annotated[
        RoleEnum | None,
        Field(
            description='User role within the tenant.\n\n* `admin` - Administrator\n* `collector` - Collector\n* `operator` - Operator\n* `viewer` - Viewer'
        ),
    ] = None
    first_name: Annotated[str | None, Field(max_length=150)] = None
    last_name: Annotated[str | None, Field(max_length=150)] = None
    email: Annotated[EmailStr | None, Field(description='User email address.', max_length=254)] = (
        None
    )
    created_at: Annotated[AwareDatetime, Field(description='When the user was created.')]
    updated_at: Annotated[AwareDatetime, Field(description='When the user was last updated.')]
    last_login: AwareDatetime | None = None


class UserDetailRequest(APIModel):
    username: Annotated[
        str,
        Field(
            description='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.',
            max_length=150,
            min_length=1,
            pattern='^[\\w.@+-]+$',
        ),
    ]
    password: Annotated[str, Field(min_length=1)]
    is_active: Annotated[
        bool | None,
        Field(
            description='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.',
            title='Active',
        ),
    ] = None
    role: Annotated[
        RoleEnum | None,
        Field(
            description='User role within the tenant.\n\n* `admin` - Administrator\n* `collector` - Collector\n* `operator` - Operator\n* `viewer` - Viewer'
        ),
    ] = None
    first_name: Annotated[str | None, Field(max_length=150)] = None
    last_name: Annotated[str | None, Field(max_length=150)] = None
    email: Annotated[EmailStr | None, Field(description='User email address.', max_length=254)] = (
        None
    )


class UserList(APIModel):
    id: Annotated[str, Field(description='Unique identifier for the user.')]
    username: Annotated[
        str,
        Field(description='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.'),
    ]
    is_active: Annotated[
        bool,
        Field(
            description='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.',
            title='Active',
        ),
    ]
    role: Annotated[
        RoleEnum,
        Field(
            description='User role within the tenant.\n\n* `admin` - Administrator\n* `collector` - Collector\n* `operator` - Operator\n* `viewer` - Viewer'
        ),
    ]
    first_name: str
    last_name: str
    email: Annotated[EmailStr | None, Field(description='User email address.')] = None
    created_at: Annotated[AwareDatetime, Field(description='When the user was created.')]
    updated_at: Annotated[AwareDatetime, Field(description='When the user was last updated.')]
    last_login: AwareDatetime | None = None


class VLAN(APIModel):
    id: str
    device: Annotated[str, Field(description='The device this VLAN belongs to.')]
    device_hostname: str
    vlan_id: Annotated[int, Field(description='VLAN ID (1-4094).', ge=-2147483648, le=2147483647)]
    name: Annotated[str | None, Field(description='VLAN name.', max_length=100)] = None
    state: Annotated[
        StateEnum | None,
        Field(description='VLAN state.\n\n* `active` - Active\n* `suspend` - Suspended'),
    ] = None


class RtImportItem(RootModel[str]):
    root: Annotated[str, Field(max_length=32)]


class RtExportItem(RootModel[str]):
    root: Annotated[str, Field(max_length=32)]


class VRF(APIModel):
    id: str
    device: Annotated[str, Field(description='The device this VRF belongs to.')]
    device_hostname: str
    name: Annotated[str, Field(description='VRF name.', max_length=100)]
    rd: Annotated[str | None, Field(description='Route Distinguisher.', max_length=50)] = None
    rt_import: Annotated[list[RtImportItem] | None, Field(description='Import Route Targets.')] = (
        None
    )
    rt_export: Annotated[list[RtExportItem] | None, Field(description='Export Route Targets.')] = (
        None
    )
    description: Annotated[str | None, Field(description='VRF description.', max_length=255)] = None


class VirtualizationTypeEnum(Enum):
    container = 'container'
    physical = 'physical'
    stack = 'stack'
    vdc = 'vdc'
    vm = 'vm'


class CanonicalDeviceDetail(APIModel):
    id: Annotated[str, Field(description='Unique identifier for the canonical device.')]
    label: Annotated[
        str,
        Field(
            description='Display name.',
            max_length=255,
            pattern='^(?:[a-zA-Z0-9_](?:[a-zA-Z0-9\\-_]{0,61}[a-zA-Z0-9_])?\\.)+[a-zA-Z]{2,}$|^[a-zA-Z0-9_](?:[a-zA-Z0-9\\-_]{0,61}[a-zA-Z0-9_])?$',
        ),
    ]
    icon: Annotated[
        IconEnum | BlankEnum | NullEnum | None,
        Field(
            description='Icon used to represent the device in topologies.\n\n* `firewall` - Firewall\n* `load-balancer` - Load Balancer\n* `phone` - Phone\n* `router` - Router\n* `router-modular` - Modular Router\n* `switch-l2` - Switch L2\n* `switch-l3` - Switch L3\n* `switch-modular` - Modular Switch\n* `wireless-ap` - Wireless Access Point\n* `wireless-controller` - Wireless Controller\n* `workstation` - Workstation'
        ),
    ] = None
    mgmt_address: Annotated[
        str | None,
        Field(
            description='Primary address for discovery.', max_length=255, title='Management address'
        ),
    ] = None
    discovery_mode: Annotated[
        DiscoveryModeEnum | BlankEnum | NullEnum | None,
        Field(
            description='Discovery mode.\n\n* `netmiko:allied_telesis:awplus:ssh` - Allied Telesis AW+ (SSH)\n* `netmiko:aruba:aoscx:ssh` - Aruba AOSCX (SSH)\n* `netmiko:cisco:ios:ssh` - Cisco IOS XE (SSH)\n* `netmiko:cisco:ios:telnet` - Cisco IOS XE (Telnet)\n* `netmiko:cisco:nxos:ssh` - Cisco NX-OS (SSH)\n* `netmiko:cisco_xr:ssh` - Cisco XR (SSH)\n* `netmiko:hp:comware:ssh` - HPE Comware (SSH)\n* `netmiko:hp:procurve:ssh` - HPE Procurve (SSH)\n* `netmiko:hp:procurve:telnet` - HPE Procurve (Telnet)\n* `netmiko:huawei:vrp:ssh` - Huawei VRP (SSH)\n* `netmiko:linux::ssh` - Linux (SSH)\n* `netdoc:panw:ngfw:https` - Palo Alto Networks NGFW (HTTPs)\n* `netdoc:vmware:vsphere:https` - VMware vSphere (HTTPs)'
        ),
    ] = None
    is_discoverable: Annotated[
        bool | None,
        Field(
            description='Whether the device is still actively discovered.', title='Is discoverable?'
        ),
    ] = None
    identifiers: Annotated[Any, Field(description='Unique identifiers to correlate the device.')]
    credential: Annotated[str | None, Field(description='Credential used to discovery.')] = None
    parent: Annotated[
        str | None, Field(description='Parent device for virtual instances (e.g., N7K VDC).')
    ] = None
    site: Annotated[str | None, Field(description='Canonical site/location for this device.')] = (
        None
    )
    site_name: str | None = None
    role: Annotated[
        str | None,
        Field(
            description='Device role (core, distribution, access, etc.).',
            max_length=100,
            pattern='^[\\w\\s\\-]+$',
        ),
    ] = None
    created_at: Annotated[AwareDatetime, Field(description='When this site was created.')]
    updated_at: Annotated[AwareDatetime, Field(description='When this site was last updated.')]
    first_seen: Annotated[
        AwareDatetime | None, Field(description='When this device was first discovered.')
    ] = None
    last_seen: Annotated[
        AwareDatetime | None, Field(description='When this device was last seen in a snapshot.')
    ] = None
    inactive_since: Annotated[
        AwareDatetime | None,
        Field(description='When the device became inactive (not seen in snapshots).'),
    ] = None
    is_active: Annotated[
        bool,
        Field(
            description='Whether the device is still being seen in snapshots.', title='Is active?'
        ),
    ]


class CanonicalDeviceDetailRequest(APIModel):
    label: Annotated[
        str,
        Field(
            description='Display name.',
            max_length=255,
            min_length=1,
            pattern='^(?:[a-zA-Z0-9_](?:[a-zA-Z0-9\\-_]{0,61}[a-zA-Z0-9_])?\\.)+[a-zA-Z]{2,}$|^[a-zA-Z0-9_](?:[a-zA-Z0-9\\-_]{0,61}[a-zA-Z0-9_])?$',
        ),
    ]
    icon: Annotated[
        IconEnum | BlankEnum | NullEnum | None,
        Field(
            description='Icon used to represent the device in topologies.\n\n* `firewall` - Firewall\n* `load-balancer` - Load Balancer\n* `phone` - Phone\n* `router` - Router\n* `router-modular` - Modular Router\n* `switch-l2` - Switch L2\n* `switch-l3` - Switch L3\n* `switch-modular` - Modular Switch\n* `wireless-ap` - Wireless Access Point\n* `wireless-controller` - Wireless Controller\n* `workstation` - Workstation'
        ),
    ] = None
    mgmt_address: Annotated[
        str | None,
        Field(
            description='Primary address for discovery.', max_length=255, title='Management address'
        ),
    ] = None
    discovery_mode: Annotated[
        DiscoveryModeEnum | BlankEnum | NullEnum | None,
        Field(
            description='Discovery mode.\n\n* `netmiko:allied_telesis:awplus:ssh` - Allied Telesis AW+ (SSH)\n* `netmiko:aruba:aoscx:ssh` - Aruba AOSCX (SSH)\n* `netmiko:cisco:ios:ssh` - Cisco IOS XE (SSH)\n* `netmiko:cisco:ios:telnet` - Cisco IOS XE (Telnet)\n* `netmiko:cisco:nxos:ssh` - Cisco NX-OS (SSH)\n* `netmiko:cisco_xr:ssh` - Cisco XR (SSH)\n* `netmiko:hp:comware:ssh` - HPE Comware (SSH)\n* `netmiko:hp:procurve:ssh` - HPE Procurve (SSH)\n* `netmiko:hp:procurve:telnet` - HPE Procurve (Telnet)\n* `netmiko:huawei:vrp:ssh` - Huawei VRP (SSH)\n* `netmiko:linux::ssh` - Linux (SSH)\n* `netdoc:panw:ngfw:https` - Palo Alto Networks NGFW (HTTPs)\n* `netdoc:vmware:vsphere:https` - VMware vSphere (HTTPs)'
        ),
    ] = None
    is_discoverable: Annotated[
        bool | None,
        Field(
            description='Whether the device is still actively discovered.', title='Is discoverable?'
        ),
    ] = None
    identifiers: Annotated[Any, Field(description='Unique identifiers to correlate the device.')]
    credential: Annotated[str | None, Field(description='Credential used to discovery.')] = None
    parent: Annotated[
        str | None, Field(description='Parent device for virtual instances (e.g., N7K VDC).')
    ] = None
    site: Annotated[str | None, Field(description='Canonical site/location for this device.')] = (
        None
    )
    role: Annotated[
        str | None,
        Field(
            description='Device role (core, distribution, access, etc.).',
            max_length=100,
            pattern='^[\\w\\s\\-]+$',
        ),
    ] = None


class CanonicalDeviceList(APIModel):
    id: Annotated[str, Field(description='Unique identifier for the canonical device.')]
    label: Annotated[str, Field(description='Display name.')]
    icon: Annotated[
        IconEnum | NullEnum | None,
        Field(
            description='Icon used to represent the device in topologies.\n\n* `firewall` - Firewall\n* `load-balancer` - Load Balancer\n* `phone` - Phone\n* `router` - Router\n* `router-modular` - Modular Router\n* `switch-l2` - Switch L2\n* `switch-l3` - Switch L3\n* `switch-modular` - Modular Switch\n* `wireless-ap` - Wireless Access Point\n* `wireless-controller` - Wireless Controller\n* `workstation` - Workstation'
        ),
    ] = None
    mgmt_address: Annotated[
        str | None, Field(description='Primary address for discovery.', title='Management address')
    ] = None
    discovery_mode: Annotated[
        DiscoveryModeEnum | NullEnum | None,
        Field(
            description='Discovery mode.\n\n* `netmiko:allied_telesis:awplus:ssh` - Allied Telesis AW+ (SSH)\n* `netmiko:aruba:aoscx:ssh` - Aruba AOSCX (SSH)\n* `netmiko:cisco:ios:ssh` - Cisco IOS XE (SSH)\n* `netmiko:cisco:ios:telnet` - Cisco IOS XE (Telnet)\n* `netmiko:cisco:nxos:ssh` - Cisco NX-OS (SSH)\n* `netmiko:cisco_xr:ssh` - Cisco XR (SSH)\n* `netmiko:hp:comware:ssh` - HPE Comware (SSH)\n* `netmiko:hp:procurve:ssh` - HPE Procurve (SSH)\n* `netmiko:hp:procurve:telnet` - HPE Procurve (Telnet)\n* `netmiko:huawei:vrp:ssh` - Huawei VRP (SSH)\n* `netmiko:linux::ssh` - Linux (SSH)\n* `netdoc:panw:ngfw:https` - Palo Alto Networks NGFW (HTTPs)\n* `netdoc:vmware:vsphere:https` - VMware vSphere (HTTPs)'
        ),
    ] = None
    is_discoverable: Annotated[
        bool,
        Field(
            description='Whether the device is still actively discovered.', title='Is discoverable?'
        ),
    ]
    parent: Annotated[
        str | None, Field(description='Parent device for virtual instances (e.g., N7K VDC).')
    ] = None
    site: Annotated[str | None, Field(description='Canonical site/location for this device.')] = (
        None
    )
    site_name: str | None = None
    role: Annotated[
        str | None, Field(description='Device role (core, distribution, access, etc.).')
    ] = None
    created_at: Annotated[AwareDatetime, Field(description='When this site was created.')]
    updated_at: Annotated[AwareDatetime, Field(description='When this site was last updated.')]
    first_seen: Annotated[
        AwareDatetime | None, Field(description='When this device was first discovered.')
    ] = None
    last_seen: Annotated[
        AwareDatetime | None, Field(description='When this device was last seen in a snapshot.')
    ] = None
    inactive_since: Annotated[
        AwareDatetime | None,
        Field(description='When the device became inactive (not seen in snapshots).'),
    ] = None
    is_active: Annotated[
        bool,
        Field(
            description='Whether the device is still being seen in snapshots.', title='Is active?'
        ),
    ]


class CanonicalEndpoint(APIModel):
    id: Annotated[str, Field(description='Unique identifier for the canonical endpoint.')]
    instance_id: Annotated[
        str | None,
        Field(
            description='Hypervisor/cloud instance identifier (VM moref, AWS instance-id).',
            max_length=255,
        ),
    ] = None
    hypervisor_type: Annotated[
        HypervisorTypeEnum | None,
        Field(
            description='Type of hypervisor or platform.\n\n* `vsphere` - VMware vSphere\n* `hyperv` - Microsoft Hyper-V\n* `kvm` - KVM/QEMU\n* `aws` - Amazon Web Services\n* `azure` - Microsoft Azure\n* `gcp` - Google Cloud Platform\n* `docker` - Docker\n* `kubernetes` - Kubernetes\n* `baremetal` - Bare Metal\n* `unknown` - Unknown'
        ),
    ] = None
    primary_mac: Annotated[
        str | None, Field(description='Primary MAC address for correlation.', max_length=17)
    ] = None
    primary_hostname: Annotated[
        str | None, Field(description='Primary hostname for correlation.', max_length=255)
    ] = None
    first_seen: Annotated[
        AwareDatetime, Field(description='When this endpoint was first discovered.')
    ]
    last_seen: Annotated[
        AwareDatetime, Field(description='When this endpoint was last seen in a snapshot.')
    ]
    is_active: Annotated[
        bool | None, Field(description='Whether the endpoint is still being seen in snapshots.')
    ] = None


class DeviceConnectionDetail(APIModel):
    id: Annotated[str, Field(description='Unique identifier for the connection.')]
    snapshot: Annotated[str, Field(description='The snapshot this data belongs to.')]
    interface_a: Annotated[
        str, Field(description='First interface of the connection (lower UUID).')
    ]
    device_a: str
    interface_a_name: str
    interface_b: Annotated[
        str, Field(description='Second interface of the connection (higher UUID).')
    ]
    device_b: str
    interface_b_name: str
    connection_type: Annotated[
        ConnectionTypeEc9Enum | None,
        Field(
            description='Type of connection.\n\n* `physical` - Physical\n* `logical` - Logical\n* `virtual` - Virtual'
        ),
    ] = None
    discovered_via: Annotated[
        DiscoveredVia9dcEnum | None,
        Field(
            description='How the connection was discovered.\n\n* `inferred` - Inferred\n* `lldp` - LLDP\n* `cdp` - CDP\n* `manual` - Manual\n* `arp` - ARP Table\n* `mac_table` - MAC Address Table'
        ),
    ] = None
    is_inter_device: bool


class DeviceConnectionList(APIModel):
    id: Annotated[str, Field(description='Unique identifier for the connection.')]
    interface_a: Annotated[
        str, Field(description='First interface of the connection (lower UUID).')
    ]
    device_a: str
    interface_a_name: str
    interface_b: Annotated[
        str, Field(description='Second interface of the connection (higher UUID).')
    ]
    device_b: str
    interface_b_name: str
    connection_type: Annotated[
        ConnectionTypeEc9Enum | None,
        Field(
            description='Type of connection.\n\n* `physical` - Physical\n* `logical` - Logical\n* `virtual` - Virtual'
        ),
    ] = None
    discovered_via: Annotated[
        DiscoveredVia9dcEnum | None,
        Field(
            description='How the connection was discovered.\n\n* `inferred` - Inferred\n* `lldp` - LLDP\n* `cdp` - CDP\n* `manual` - Manual\n* `arp` - ARP Table\n* `mac_table` - MAC Address Table'
        ),
    ] = None


class DeviceList(APIModel):
    id: Annotated[str | None, Field(description='Unique identifier for the device.')] = None
    canonical_device: Annotated[
        str | None, Field(description='Reference to stable identity across snapshots.')
    ] = None
    hostname: Annotated[str, Field(description='Device hostname.', max_length=255)]
    fqdn: Annotated[
        str | None, Field(description='Fully qualified domain name.', max_length=255)
    ] = None
    device_models: Annotated[
        list[DeviceModel] | None,
        Field(
            description='List of device models (nexus-9300, catalyst-9500, etc.).', title='Models'
        ),
    ] = None
    platform: Annotated[
        str | None,
        Field(description='Operating system/platform (nxos, ios-xe, eos).', max_length=100),
    ] = None
    serial_numbers: Annotated[
        list[SerialNumber] | None, Field(description='List of device serial numbers.')
    ] = None
    software_version: Annotated[
        str | None,
        Field(description='Running software version.', max_length=100, title='SW version'),
    ] = None
    vendor: Annotated[
        str | None,
        Field(description='Device vendor (cisco, arista, juniper, etc.).', max_length=100),
    ] = None
    virtualization_type: Annotated[
        VirtualizationTypeEnum | None,
        Field(
            description='Type of device virtualization.\n\n* `container` - Container\n* `physical` - Physical\n* `stack` - Stack\n* `vdc` - Virtual Device Context\n* `vm` - Virtual Machine'
        ),
    ] = None
    interface_count: int
    uptime_seconds: Annotated[
        int | None,
        Field(
            description='Device update im seconds',
            ge=-9223372036854775808,
            le=9223372036854775807,
            title='Uptime (sec)',
        ),
    ] = None


class DiscoveredDeviceLogRequest(APIModel):
    level: Annotated[
        LevelEnum,
        Field(
            description='Severity level of the log record.\n\n* `DEBUG` - Debug\n* `INFO` - Info\n* `WARNING` - Warning\n* `ERROR` - Error\n* `CRITICAL` - Critical'
        ),
    ]
    message: Annotated[str, Field(description='The formatted log message.', min_length=1)]
    context: Annotated[
        Any | None, Field(description='Arbitrary structured context for the event.')
    ] = None
    exception_type: Annotated[
        str | None,
        Field(
            description='Exception class name, when the record captured an exception.',
            max_length=255,
        ),
    ] = None
    traceback: Annotated[str | None, Field(description='Formatted traceback, when available.')] = (
        None
    )
    module: Annotated[
        str | None, Field(description='Module that emitted the record.', max_length=255)
    ] = None
    func_name: Annotated[
        str | None,
        Field(
            description='Function that emitted the record.', max_length=255, title='Function name'
        ),
    ] = None
    line_no: Annotated[
        int | None,
        Field(
            description='Source line number that emitted the record.',
            ge=-2147483648,
            le=2147483647,
            title='Line number',
        ),
    ] = None
    hostname: Annotated[
        str | None,
        Field(description='Hostname of the process that emitted the record.', max_length=255),
    ] = None
    process: Annotated[
        int | None,
        Field(description='Process id that emitted the record.', ge=-2147483648, le=2147483647),
    ] = None
    thread_name: Annotated[
        str | None, Field(description='Thread name that emitted the record.', max_length=255)
    ] = None


class DiscoveredDeviceSubmitRequest(APIModel):
    logs: Annotated[
        list[DiscoveredDeviceLogRequest] | None,
        Field(description='Log entries collected by the collector while processing the device.'),
    ] = None
    raw_payload: Annotated[
        Any | None,
        Field(
            description='Raw data collected from the device of key-value pairs. Keys are the commands executed on the device, values are the command outputs.'
        ),
    ] = None
    idempotency_key: str | None = ''
    canonical_device: Annotated[
        str, Field(description='Unique identifier for the canonical device.')
    ]
    attempt: Annotated[int | None, Field(ge=1)] = None


class DiscoveryJobCompleteRequest(APIModel):
    logs: Annotated[
        list[DiscoveredDeviceLogRequest] | None,
        Field(description='Log entries collected by the collector while processing the job.'),
    ] = None
    status: DiscoveryJobCompleteStatusEnum


class DiscoveryJobDetail(APIModel):
    id: Annotated[str, Field(description='Unique identifier for the job.')]
    canonical_devices: list[CanonicalDeviceDetail]
    collector: Annotated[str, Field(description='Collector responsable for the job.')]
    collector_name: str
    idempotency_key: Annotated[str, Field(description='Idempotency key.')]
    run: Annotated[str, Field(description='Associated discovery run.', title='Discovery')]
    status: Annotated[
        StatusF5fEnum,
        Field(
            description='Job status.\n\n* `cancelled` - Cancelled\n* `cancelling` - Cancelling\n* `claimed` - Claimed\n* `completed` - Completed\n* `expired` - Expired\n* `failed` - Failed\n* `queued` - Queued\n* `running` - Running'
        ),
    ]
    attempt: Annotated[int, Field(description='Current attempt.')]
    max_attempts: Annotated[int, Field(description='Maximum allowed attempts.')]
    cancellation_acknowledged_at: Annotated[
        AwareDatetime | None, Field(description='When the job has been cancelled by the collector.')
    ] = None
    claimed_at: Annotated[
        AwareDatetime | None, Field(description='When the job has been claimed by the collector.')
    ] = None
    created_at: Annotated[AwareDatetime, Field(description='When the job was created.')]
    last_heartbeat_at: Annotated[
        AwareDatetime | None, Field(description='When the job has been reported by the collector.')
    ] = None
    lease_expires_at: Annotated[
        AwareDatetime | None, Field(description='When the lease expires.')
    ] = None
    timeout_at: Annotated[
        AwareDatetime | None, Field(description='Timeout datetime if no heartbeat occurs.')
    ] = None
    updated_at: Annotated[AwareDatetime, Field(description='When the job was last updated.')]


class DiscoveryJobStatus(APIModel):
    status: Annotated[
        StatusF5fEnum,
        Field(
            description='Job status.\n\n* `cancelled` - Cancelled\n* `cancelling` - Cancelling\n* `claimed` - Claimed\n* `completed` - Completed\n* `expired` - Expired\n* `failed` - Failed\n* `queued` - Queued\n* `running` - Running'
        ),
    ]
    attempt: Annotated[int, Field(description='Current attempt.')]
    max_attempts: Annotated[int, Field(description='Maximum allowed attempts.')]
    cancellation_acknowledged_at: Annotated[
        AwareDatetime | None, Field(description='When the job has been cancelled by the collector.')
    ] = None
    claimed_at: Annotated[
        AwareDatetime | None, Field(description='When the job has been claimed by the collector.')
    ] = None
    created_at: Annotated[AwareDatetime, Field(description='When the job was created.')]
    last_heartbeat_at: Annotated[
        AwareDatetime | None, Field(description='When the job has been reported by the collector.')
    ] = None
    lease_expires_at: Annotated[
        AwareDatetime | None, Field(description='When the lease expires.')
    ] = None
    timeout_at: Annotated[
        AwareDatetime | None, Field(description='Timeout datetime if no heartbeat occurs.')
    ] = None
    updated_at: Annotated[AwareDatetime, Field(description='When the job was last updated.')]


class DiscoveryRunDetail(APIModel):
    id: Annotated[str, Field(description='Unique identifier for the discovery.')]
    origin: Annotated[
        OriginEnum,
        Field(
            description='Origin of the discovery.\n\n* `manual` - Manual\n* `scheduled` - Scheduled'
        ),
    ]
    requested_by: Annotated[str | None, Field(description='Who requested the discovery.')] = None
    schedule: Annotated[
        str | None,
        Field(description='Schedule associated to the discovery.', title='Associated schedule'),
    ] = None
    snapshot: Annotated[str | None, Field(description='Snapshot associated to the discovery.')] = (
        None
    )
    status: Annotated[
        DiscoveryRunDetailStatusEnum,
        Field(
            description='Discovery status.\n\n* `pending` - Pending\n* `running` - Running\n* `cancelling` - Cancelling\n* `cancelled` - Cancelled\n* `completed` - Completed\n* `failed` - Failed'
        ),
    ]
    completed_job_count: Annotated[
        int, Field(description='Number of completed jobs.', title='Completed')
    ]
    failed_job_count: Annotated[int, Field(description='Number of failed jobs.', title='Failed')]
    job_count: Annotated[int, Field(description='Total number of jobs.', title='Jobs')]
    parsed_output_count: Annotated[int, Field(description='Number of parsed logs.', title='Parsed')]
    raw_output_count: Annotated[int, Field(description='Number of output logs.', title='Logs')]
    cancellation_requested_at: Annotated[
        AwareDatetime | None,
        Field(description='When the run has been cancelled.', title='Cancelled at'),
    ] = None
    completed_at: Annotated[
        AwareDatetime | None, Field(description='When the run has been completed.')
    ] = None
    created_at: Annotated[AwareDatetime, Field(description='When the discovery run was created.')]
    started_at: Annotated[
        AwareDatetime | None, Field(description='When the discovery run has been started.')
    ] = None
    updated_at: Annotated[
        AwareDatetime, Field(description='When the discovery run was last updated.')
    ]


class EndpointDetail(APIModel):
    id: Annotated[str, Field(description='Unique identifier for the endpoint.')]
    canonical_endpoint: CanonicalEndpoint
    name: Annotated[
        str | None, Field(description='Endpoint name/hostname if known.', max_length=255)
    ] = None
    endpoint_type: Annotated[
        EndpointTypeEnum | None,
        Field(
            description='Type of endpoint.\n\n* `server` - Server\n* `client` - Client\n* `vm` - Virtual Machine\n* `storage` - Storage System\n* `iot` - IoT Device\n* `printer` - Printer\n* `phone` - IP Phone\n* `other` - Other'
        ),
    ] = None
    discovered_via: Annotated[
        DiscoveredVia09dEnum | None,
        Field(
            description='How this endpoint was discovered.\n\n* `arp` - ARP Table\n* `mac_table` - MAC Address Table\n* `dhcp` - DHCP\n* `lldp` - LLDP\n* `cdp` - CDP\n* `manual` - Manual\n* `api` - External API'
        ),
    ] = None
    discovered_on_device: Annotated[
        str, Field(description='Network device where this endpoint was discovered.')
    ]
    discovered_on_device_hostname: str | None = None
    discovered_on_interface: Annotated[
        str | None, Field(description='Interface where this endpoint was discovered.')
    ] = None
    discovered_on_interface_name: str | None = None
    interfaces: list[EndpointInterface]


class EndpointList(APIModel):
    id: Annotated[str | None, Field(description='Unique identifier for the endpoint.')] = None
    name: Annotated[
        str | None, Field(description='Endpoint name/hostname if known.', max_length=255)
    ] = None
    endpoint_type: Annotated[
        EndpointTypeEnum | None,
        Field(
            description='Type of endpoint.\n\n* `server` - Server\n* `client` - Client\n* `vm` - Virtual Machine\n* `storage` - Storage System\n* `iot` - IoT Device\n* `printer` - Printer\n* `phone` - IP Phone\n* `other` - Other'
        ),
    ] = None
    discovered_via: Annotated[
        DiscoveredVia09dEnum | None,
        Field(
            description='How this endpoint was discovered.\n\n* `arp` - ARP Table\n* `mac_table` - MAC Address Table\n* `dhcp` - DHCP\n* `lldp` - LLDP\n* `cdp` - CDP\n* `manual` - Manual\n* `api` - External API'
        ),
    ] = None
    discovered_on_device: Annotated[
        str, Field(description='Network device where this endpoint was discovered.')
    ]
    discovered_on_device_hostname: str | None = None
    discovered_on_interface: Annotated[
        str | None, Field(description='Interface where this endpoint was discovered.')
    ] = None
    discovered_on_interface_name: str | None = None
    interface_count: int


class InterfaceDetail(APIModel):
    id: Annotated[str, Field(description='Unique identifier for the interface.')]
    device: Annotated[str, Field(description='The device this interface belongs to.')]
    device_hostname: str
    name: Annotated[
        str, Field(description='Interface name (Ethernet1/1, Vlan100, etc.).', max_length=100)
    ]
    description: Annotated[
        str | None, Field(description='Interface description.', max_length=255)
    ] = None
    interface_type: Annotated[
        InterfaceTypeEnum | None,
        Field(
            description='Type of interface.\n\n* `loopback` - Loopback\n* `management` - Management\n* `nve` - NVE\n* `other` - Other\n* `physical` - Physical\n* `port_channel` - Port Channel\n* `subinterface` - Subinterface\n* `tunnel` - Tunnel\n* `virtual` - Virtual\n* `vlan_svi` - VLAN SVI',
            title='Type',
        ),
    ] = None
    inactive_since: Annotated[
        AwareDatetime | None,
        Field(description='When the interface became inactive.', title='Last activity'),
    ] = None
    mac_address: Annotated[
        str | None, Field(description='Interface MAC address (AA:BB:CC:DD:EE:FF).', max_length=17)
    ] = None
    speed_mbps: Annotated[
        int | None,
        Field(
            description='Link speed in Mbps.',
            ge=-9223372036854775808,
            le=9223372036854775807,
            title='Speed (Mbps)',
        ),
    ] = None
    mtu: Annotated[
        int | None, Field(description='Maximum transmission unit.', ge=-2147483648, le=2147483647)
    ] = None
    admin_state: Annotated[
        AdminStateEnum | None,
        Field(description='Administrative state.\n\n* `down` - Down\n* `up` - Up'),
    ] = None
    oper_state: Annotated[
        OperStateEnum | None,
        Field(
            description='Operational state.\n\n* `down` - Down\n* `unknown` - Unknown\n* `up` - Up',
            title='Operation state',
        ),
    ] = None
    switchport_mode: Annotated[
        SwitchportModeEnum | BlankEnum | NullEnum | None,
        Field(
            description='Switchport mode.\n\n* `access` - Access\n* `hybrid` - Hybrid\n* `routed` - Routed (L3)\n* `trunk` - Trunk'
        ),
    ] = None
    native_vlan: Annotated[str | None, Field(description='Native VLAN for trunk ports.')] = None
    native_vlan_id: int | None = None
    allowed_vlan_ids: list[int]
    vrf: Annotated[str | None, Field(description='VRF this interface belongs to.')] = None
    vrf_name: str | None = None
    parent: Annotated[
        str | None, Field(description='Parent interface for Port-Channels, sub-interfaces.')
    ] = None
    tunnel_type: Annotated[
        InterfaceDetailTunnelTypeEnum | BlankEnum | None,
        Field(
            description='Tunnel type (vxlan, gre, geneve).\n\n* `geneve` - GENEVE\n* `gre` - GRE\n* `ipsec` - IPSEC\n* `mpls` - MPLS\n* `none` - None\n* `other` - Other\n* `vxlan` - VXLAN'
        ),
    ] = None
    tunnel_src: Annotated[
        str | None, Field(description='Tunnel source IP.', title='Tunnel source')
    ] = None
    tunnel_dst: Annotated[
        str | None, Field(description='Tunnel destination IP.', title='Tunnel destination')
    ] = None
    tunnel_vni: Annotated[
        int | None,
        Field(description='VNI/VSID for overlay tunnels.', ge=-2147483648, le=2147483647),
    ] = None
    ip_addresses: list[IPAddress]


class InterfaceList(APIModel):
    id: Annotated[str | None, Field(description='Unique identifier for the interface.')] = None
    name: Annotated[
        str, Field(description='Interface name (Ethernet1/1, Vlan100, etc.).', max_length=100)
    ]
    interface_type: Annotated[
        InterfaceTypeEnum | None,
        Field(
            description='Type of interface.\n\n* `loopback` - Loopback\n* `management` - Management\n* `nve` - NVE\n* `other` - Other\n* `physical` - Physical\n* `port_channel` - Port Channel\n* `subinterface` - Subinterface\n* `tunnel` - Tunnel\n* `virtual` - Virtual\n* `vlan_svi` - VLAN SVI',
            title='Type',
        ),
    ] = None
    inactive_since: Annotated[
        AwareDatetime | None,
        Field(description='When the interface became inactive.', title='Last activity'),
    ] = None
    admin_state: Annotated[
        AdminStateEnum | None,
        Field(description='Administrative state.\n\n* `down` - Down\n* `up` - Up'),
    ] = None
    oper_state: Annotated[
        OperStateEnum | None,
        Field(
            description='Operational state.\n\n* `down` - Down\n* `unknown` - Unknown\n* `up` - Up',
            title='Operation state',
        ),
    ] = None
    switchport_mode: Annotated[
        SwitchportModeEnum | BlankEnum | NullEnum | None,
        Field(
            description='Switchport mode.\n\n* `access` - Access\n* `hybrid` - Hybrid\n* `routed` - Routed (L3)\n* `trunk` - Trunk'
        ),
    ] = None


class PaginatedCanonicalDeviceListList(APIModel):
    count: Annotated[int, Field(examples=[123])]
    next: Annotated[AnyUrl | None, Field(examples=['http://api.example.org/accounts/?page=4'])] = (
        None
    )
    previous: Annotated[
        AnyUrl | None, Field(examples=['http://api.example.org/accounts/?page=2'])
    ] = None
    results: list[CanonicalDeviceList]


class PaginatedCanonicalEndpointList(APIModel):
    count: Annotated[int, Field(examples=[123])]
    next: Annotated[AnyUrl | None, Field(examples=['http://api.example.org/accounts/?page=4'])] = (
        None
    )
    previous: Annotated[
        AnyUrl | None, Field(examples=['http://api.example.org/accounts/?page=2'])
    ] = None
    results: list[CanonicalEndpoint]


class PaginatedDeviceConnectionListList(APIModel):
    count: Annotated[int, Field(examples=[123])]
    next: Annotated[AnyUrl | None, Field(examples=['http://api.example.org/accounts/?page=4'])] = (
        None
    )
    previous: Annotated[
        AnyUrl | None, Field(examples=['http://api.example.org/accounts/?page=2'])
    ] = None
    results: list[DeviceConnectionList]


class PaginatedDeviceListList(APIModel):
    count: Annotated[int, Field(examples=[123])]
    next: Annotated[AnyUrl | None, Field(examples=['http://api.example.org/accounts/?page=4'])] = (
        None
    )
    previous: Annotated[
        AnyUrl | None, Field(examples=['http://api.example.org/accounts/?page=2'])
    ] = None
    results: list[DeviceList]


class PaginatedDiscoveryJobDetailList(APIModel):
    count: Annotated[int, Field(examples=[123])]
    next: Annotated[AnyUrl | None, Field(examples=['http://api.example.org/accounts/?page=4'])] = (
        None
    )
    previous: Annotated[
        AnyUrl | None, Field(examples=['http://api.example.org/accounts/?page=2'])
    ] = None
    results: list[DiscoveryJobDetail]


class PaginatedDiscoveryRunDetailList(APIModel):
    count: Annotated[int, Field(examples=[123])]
    next: Annotated[AnyUrl | None, Field(examples=['http://api.example.org/accounts/?page=4'])] = (
        None
    )
    previous: Annotated[
        AnyUrl | None, Field(examples=['http://api.example.org/accounts/?page=2'])
    ] = None
    results: list[DiscoveryRunDetail]


class PaginatedEndpointListList(APIModel):
    count: Annotated[int, Field(examples=[123])]
    next: Annotated[AnyUrl | None, Field(examples=['http://api.example.org/accounts/?page=4'])] = (
        None
    )
    previous: Annotated[
        AnyUrl | None, Field(examples=['http://api.example.org/accounts/?page=2'])
    ] = None
    results: list[EndpointList]


class PaginatedInterfaceListList(APIModel):
    count: Annotated[int, Field(examples=[123])]
    next: Annotated[AnyUrl | None, Field(examples=['http://api.example.org/accounts/?page=4'])] = (
        None
    )
    previous: Annotated[
        AnyUrl | None, Field(examples=['http://api.example.org/accounts/?page=2'])
    ] = None
    results: list[InterfaceList]


class PaginatedRouteEntryList(APIModel):
    count: Annotated[int, Field(examples=[123])]
    next: Annotated[AnyUrl | None, Field(examples=['http://api.example.org/accounts/?page=4'])] = (
        None
    )
    previous: Annotated[
        AnyUrl | None, Field(examples=['http://api.example.org/accounts/?page=2'])
    ] = None
    results: list[RouteEntry]


class PaginatedTenantListList(APIModel):
    count: Annotated[int, Field(examples=[123])]
    next: Annotated[AnyUrl | None, Field(examples=['http://api.example.org/accounts/?page=4'])] = (
        None
    )
    previous: Annotated[
        AnyUrl | None, Field(examples=['http://api.example.org/accounts/?page=2'])
    ] = None
    results: list[TenantList]


class PaginatedUserListList(APIModel):
    count: Annotated[int, Field(examples=[123])]
    next: Annotated[AnyUrl | None, Field(examples=['http://api.example.org/accounts/?page=4'])] = (
        None
    )
    previous: Annotated[
        AnyUrl | None, Field(examples=['http://api.example.org/accounts/?page=2'])
    ] = None
    results: list[UserList]


class PaginatedVLANList(APIModel):
    count: Annotated[int, Field(examples=[123])]
    next: Annotated[AnyUrl | None, Field(examples=['http://api.example.org/accounts/?page=4'])] = (
        None
    )
    previous: Annotated[
        AnyUrl | None, Field(examples=['http://api.example.org/accounts/?page=2'])
    ] = None
    results: list[VLAN]


class PaginatedVRFList(APIModel):
    count: Annotated[int, Field(examples=[123])]
    next: Annotated[AnyUrl | None, Field(examples=['http://api.example.org/accounts/?page=4'])] = (
        None
    )
    previous: Annotated[
        AnyUrl | None, Field(examples=['http://api.example.org/accounts/?page=2'])
    ] = None
    results: list[VRF]


class PatchedSiteDetailRequest(APIModel):
    name: Annotated[
        str | None,
        Field(
            description='Human-readable site name.',
            max_length=255,
            min_length=1,
            pattern='^[\\w\\s\\-]+$',
        ),
    ] = None
    site_type: Annotated[
        SiteTypeEnum | None,
        Field(
            description='Physical or logical site category.\n\n* `datacenter` - Datacenter\n* `campus` - Campus\n* `cloud` - Cloud\n* `branch` - Branch\n* `other` - Other'
        ),
    ] = None
    address: Annotated[
        str | None, Field(description='Optional street address or free-form location details.')
    ] = None
    city: Annotated[
        str | None, Field(description='Optional city for the site.', max_length=100)
    ] = None
    region: Annotated[
        str | None,
        Field(
            description='Optional state, province, cloud region, or similar area.', max_length=100
        ),
    ] = None
    country: Annotated[
        str | None, Field(description='Optional country for the site.', max_length=100)
    ] = None


class PatchedUserDetailRequest(APIModel):
    username: Annotated[
        str | None,
        Field(
            description='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.',
            max_length=150,
            min_length=1,
            pattern='^[\\w.@+-]+$',
        ),
    ] = None
    password: Annotated[str | None, Field(min_length=1)] = None
    is_active: Annotated[
        bool | None,
        Field(
            description='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.',
            title='Active',
        ),
    ] = None
    role: Annotated[
        RoleEnum | None,
        Field(
            description='User role within the tenant.\n\n* `admin` - Administrator\n* `collector` - Collector\n* `operator` - Operator\n* `viewer` - Viewer'
        ),
    ] = None
    first_name: Annotated[str | None, Field(max_length=150)] = None
    last_name: Annotated[str | None, Field(max_length=150)] = None
    email: Annotated[EmailStr | None, Field(description='User email address.', max_length=254)] = (
        None
    )


class RawOutputList(APIModel):
    id: Annotated[str, Field(description='Unique identifier for the log.')]
    attempt: Annotated[int, Field(description='Attempt which produced the log.')]
    canonical_device: Annotated[str, Field(description='Associated canonical device.')]
    idempotency_key: Annotated[str, Field(description='Idempotency key.')]
    job: Annotated[str, Field(description='Associated job.')]
    run: Annotated[str, Field(description='Associated discovery run.')]
    status: Annotated[
        RawOutputListStatusEnum,
        Field(
            description='Status\n\n* `failed` - Failed\n* `ignored_after_cancel` - Ignored after cancel\n* `parsed` - Parsed\n* `queued` - Queued\n* `received` - Received\n* `stale` - Stale',
            title='Parsing status.',
        ),
    ]
    created_at: Annotated[AwareDatetime, Field(description='When the log was created.')]
    processed_at: Annotated[
        AwareDatetime | None, Field(description='When the log has been processed.')
    ] = None
    updated_at: Annotated[AwareDatetime, Field(description='When the log was last updated.')]


class SiteDetail(APIModel):
    id: Annotated[str, Field(description='Unique identifier for the site.')]
    name: Annotated[
        str,
        Field(description='Human-readable site name.', max_length=255, pattern='^[\\w\\s\\-]+$'),
    ]
    site_type: Annotated[
        SiteTypeEnum | None,
        Field(
            description='Physical or logical site category.\n\n* `datacenter` - Datacenter\n* `campus` - Campus\n* `cloud` - Cloud\n* `branch` - Branch\n* `other` - Other'
        ),
    ] = None
    address: Annotated[
        str | None, Field(description='Optional street address or free-form location details.')
    ] = None
    city: Annotated[
        str | None, Field(description='Optional city for the site.', max_length=100)
    ] = None
    region: Annotated[
        str | None,
        Field(
            description='Optional state, province, cloud region, or similar area.', max_length=100
        ),
    ] = None
    country: Annotated[
        str | None, Field(description='Optional country for the site.', max_length=100)
    ] = None
    created_at: Annotated[AwareDatetime, Field(description='When this site was created.')]
    updated_at: Annotated[AwareDatetime, Field(description='When this site was last updated.')]


class SiteDetailRequest(APIModel):
    name: Annotated[
        str,
        Field(
            description='Human-readable site name.',
            max_length=255,
            min_length=1,
            pattern='^[\\w\\s\\-]+$',
        ),
    ]
    site_type: Annotated[
        SiteTypeEnum | None,
        Field(
            description='Physical or logical site category.\n\n* `datacenter` - Datacenter\n* `campus` - Campus\n* `cloud` - Cloud\n* `branch` - Branch\n* `other` - Other'
        ),
    ] = None
    address: Annotated[
        str | None, Field(description='Optional street address or free-form location details.')
    ] = None
    city: Annotated[
        str | None, Field(description='Optional city for the site.', max_length=100)
    ] = None
    region: Annotated[
        str | None,
        Field(
            description='Optional state, province, cloud region, or similar area.', max_length=100
        ),
    ] = None
    country: Annotated[
        str | None, Field(description='Optional country for the site.', max_length=100)
    ] = None


class SiteList(APIModel):
    id: Annotated[str, Field(description='Unique identifier for the site.')]
    name: Annotated[str, Field(description='Human-readable site name.')]
    site_type: Annotated[
        SiteTypeEnum,
        Field(
            description='Physical or logical site category.\n\n* `datacenter` - Datacenter\n* `campus` - Campus\n* `cloud` - Cloud\n* `branch` - Branch\n* `other` - Other'
        ),
    ]
    address: Annotated[
        str, Field(description='Optional street address or free-form location details.')
    ]
    city: Annotated[str, Field(description='Optional city for the site.')]
    region: Annotated[
        str, Field(description='Optional state, province, cloud region, or similar area.')
    ]
    country: Annotated[str, Field(description='Optional country for the site.')]
    created_at: Annotated[AwareDatetime, Field(description='When this site was created.')]
    updated_at: Annotated[AwareDatetime, Field(description='When this site was last updated.')]


class SnapshotDetail(APIModel):
    id: Annotated[str, Field(description='Unique identifier for the snapshot.')]
    label: Annotated[
        str | None, Field(description='Human-readable label for this snapshot.', max_length=255)
    ] = None
    description: Annotated[
        str | None, Field(description='Detailed description of what this snapshot contains.')
    ] = None
    status: Annotated[
        StatusAc0Enum,
        Field(
            description='Current processing status of the snapshot.\n\n* `cancelled` - Cancelled\n* `completed` - Completed\n* `failed` - Failed\n* `partial` - Partial\n* `pending` - Pending'
        ),
    ]
    pinned: Annotated[
        bool | None,
        Field(
            description='Pinned snapshots are exempt from automatic retention deletion.',
            title='Is pinned?',
        ),
    ] = None
    created_at: Annotated[AwareDatetime, Field(description='When the snapshot was created.')]
    updated_at: Annotated[AwareDatetime, Field(description='When the snapshot was last updated.')]
    completed_at: Annotated[
        AwareDatetime | None, Field(description='When the snapshot finished processing.')
    ] = None
    device_count: Annotated[int, Field(description='Get the number of devices in this snapshot.')]


class SnapshotList(APIModel):
    id: Annotated[str, Field(description='Unique identifier for the snapshot.')]
    label: Annotated[str, Field(description='Human-readable label for this snapshot.')]
    description: Annotated[
        str, Field(description='Detailed description of what this snapshot contains.')
    ]
    status: Annotated[
        StatusAc0Enum,
        Field(
            description='Current processing status of the snapshot.\n\n* `cancelled` - Cancelled\n* `completed` - Completed\n* `failed` - Failed\n* `partial` - Partial\n* `pending` - Pending'
        ),
    ]
    pinned: Annotated[
        bool,
        Field(
            description='Pinned snapshots are exempt from automatic retention deletion.',
            title='Is pinned?',
        ),
    ]
    created_at: Annotated[AwareDatetime, Field(description='When the snapshot was created.')]
    updated_at: Annotated[AwareDatetime, Field(description='When the snapshot was last updated.')]
    completed_at: Annotated[
        AwareDatetime | None, Field(description='When the snapshot finished processing.')
    ] = None
    device_count: int


class TopologyGraph(APIModel):
    nodes: list[TopologyNode]
    edges: list[TopologyEdge]
    stats: dict[str, Any]


class TunnelConnectionDetail(APIModel):
    id: Annotated[str, Field(description='Unique identifier for the connection.')]
    snapshot: Annotated[str, Field(description='The snapshot this data belongs to.')]
    interface_a: Annotated[str, Field(description='First tunnel interface (lower UUID).')]
    device_a: str
    interface_a_name: str
    interface_b: Annotated[str, Field(description='Second tunnel interface (higher UUID).')]
    device_b: str
    interface_b_name: str
    tunnel_type: Annotated[
        TunnelTypeA97Enum | None,
        Field(
            description='Type of tunnel encapsulation.\n\n* `vxlan` - VXLAN\n* `geneve` - Geneve\n* `gre` - GRE\n* `ipsec` - IPsec\n* `mpls` - MPLS\n* `other` - Other'
        ),
    ] = None
    overlay_vni: Annotated[
        int | None,
        Field(description='VNI/VSID for the overlay tunnel.', ge=-2147483648, le=2147483647),
    ] = None
    overlay_encap: Annotated[
        str | None, Field(description='Encapsulation protocol details.', max_length=20)
    ] = None
    discovered_via: Annotated[
        DiscoveredVia9dcEnum | None,
        Field(
            description='How the connection was discovered.\n\n* `inferred` - Inferred\n* `lldp` - LLDP\n* `cdp` - CDP\n* `manual` - Manual\n* `arp` - ARP Table\n* `mac_table` - MAC Address Table'
        ),
    ] = None


class TunnelConnectionList(APIModel):
    id: Annotated[str, Field(description='Unique identifier for the connection.')]
    interface_a: Annotated[str, Field(description='First tunnel interface (lower UUID).')]
    device_a: str
    interface_a_name: str
    interface_b: Annotated[str, Field(description='Second tunnel interface (higher UUID).')]
    device_b: str
    interface_b_name: str
    tunnel_type: Annotated[
        TunnelTypeA97Enum | None,
        Field(
            description='Type of tunnel encapsulation.\n\n* `vxlan` - VXLAN\n* `geneve` - Geneve\n* `gre` - GRE\n* `ipsec` - IPsec\n* `mpls` - MPLS\n* `other` - Other'
        ),
    ] = None
    overlay_vni: Annotated[
        int | None,
        Field(description='VNI/VSID for the overlay tunnel.', ge=-2147483648, le=2147483647),
    ] = None
    discovered_via: Annotated[
        DiscoveredVia9dcEnum | None,
        Field(
            description='How the connection was discovered.\n\n* `inferred` - Inferred\n* `lldp` - LLDP\n* `cdp` - CDP\n* `manual` - Manual\n* `arp` - ARP Table\n* `mac_table` - MAC Address Table'
        ),
    ] = None


class DeviceDetail(APIModel):
    id: Annotated[str, Field(description='Unique identifier for the device.')]
    canonical_device: Annotated[
        str | None, Field(description='Reference to stable identity across snapshots.')
    ] = None
    hostname: Annotated[str, Field(description='Device hostname.')]
    fqdn: Annotated[str, Field(description='Fully qualified domain name.')]
    device_models: Annotated[
        list[DeviceModel],
        Field(
            description='List of device models (nexus-9300, catalyst-9500, etc.).', title='Models'
        ),
    ]
    platform: Annotated[str, Field(description='Operating system/platform (nxos, ios-xe, eos).')]
    raw_config: Annotated[str, Field(description='Raw configuration as text (for diff).')]
    serial_numbers: Annotated[
        list[SerialNumber], Field(description='List of device serial numbers.')
    ]
    software_version: Annotated[
        str, Field(description='Running software version.', title='SW version')
    ]
    vendor: Annotated[str, Field(description='Device vendor (cisco, arista, juniper, etc.).')]
    virtualization_type: Annotated[
        VirtualizationTypeEnum,
        Field(
            description='Type of device virtualization.\n\n* `container` - Container\n* `physical` - Physical\n* `stack` - Stack\n* `vdc` - Virtual Device Context\n* `vm` - Virtual Machine'
        ),
    ]
    interface_count: int
    interfaces: list[InterfaceList]
    vrfs: list[VRF]
    vlans: list[VLAN]
    uptime_seconds: Annotated[
        int | None, Field(description='Device update im seconds', title='Uptime (sec)')
    ] = None


class PaginatedRawOutputListList(APIModel):
    count: Annotated[int, Field(examples=[123])]
    next: Annotated[AnyUrl | None, Field(examples=['http://api.example.org/accounts/?page=4'])] = (
        None
    )
    previous: Annotated[
        AnyUrl | None, Field(examples=['http://api.example.org/accounts/?page=2'])
    ] = None
    results: list[RawOutputList]


class PaginatedSiteListList(APIModel):
    count: Annotated[int, Field(examples=[123])]
    next: Annotated[AnyUrl | None, Field(examples=['http://api.example.org/accounts/?page=4'])] = (
        None
    )
    previous: Annotated[
        AnyUrl | None, Field(examples=['http://api.example.org/accounts/?page=2'])
    ] = None
    results: list[SiteList]


class PaginatedSnapshotListList(APIModel):
    count: Annotated[int, Field(examples=[123])]
    next: Annotated[AnyUrl | None, Field(examples=['http://api.example.org/accounts/?page=4'])] = (
        None
    )
    previous: Annotated[
        AnyUrl | None, Field(examples=['http://api.example.org/accounts/?page=2'])
    ] = None
    results: list[SnapshotList]


class PaginatedTunnelConnectionListList(APIModel):
    count: Annotated[int, Field(examples=[123])]
    next: Annotated[AnyUrl | None, Field(examples=['http://api.example.org/accounts/?page=4'])] = (
        None
    )
    previous: Annotated[
        AnyUrl | None, Field(examples=['http://api.example.org/accounts/?page=2'])
    ] = None
    results: list[TunnelConnectionList]
