name: CI

env:
  PYTHON_VERSION: 3.12

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

# Cancel any existing runs of this workflow for this same branch
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Checkout backend
        uses: actions/checkout@v6
        with:
          repository: NetDocLab/netdoc
          path: netdoc
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python3
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Poetry
        run: pip install --no-cache-dir poetry

      - name: Display Poetry version
        run: poetry --version

      - name: Configure Poetry
        run: poetry config virtualenvs.in-project true

      - name: Install
        run: make install

      - name: Code linting
        run: make lint

      - name: Run pre-commit
        run: make check

      - name: Tests
        run: make coverage

  snyk:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Snyk
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high
  